from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator


class WeatherPreferences(BaseModel):
    enabled: bool = True
    every_n_breaks: int = Field(default=4, ge=0, description="0 = never; 1 = every break; N = every Nth break")


class NewsVoice(BaseModel):
    """A voice+name+instructions tuple for news bulletins. Each entry is a 'character'."""

    model_config = ConfigDict(extra="forbid")

    voice: str = Field(min_length=1, description="TTS voice identifier (e.g. 'onyx', 'sage').")
    name: str | None = Field(
        default=None,
        description=(
            "Newsreader's on-air name (e.g. 'Alex Morgan'). Referenced in the bulletin "
            "intro and outro. Leave null for an anonymous bulletin."
        ),
    )
    voice_instructions: str | None = Field(
        default=None,
        description="Natural language delivery guidance passed to the TTS model.",
    )


class NewsPreferences(BaseModel):
    enabled: bool = True
    rss_url: str = "https://www.theguardian.com/world/rss"
    every_n_breaks: int = Field(default=5, ge=0)
    headline_count: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of top headlines to include in each news bulletin.",
    )
    voices: list[NewsVoice] = Field(
        default_factory=lambda: [
            NewsVoice(
                voice="onyx",
                name="Alex Morgan",
                voice_instructions=(
                    "Calm, measured newsreader. Authoritative, neutral, clearly enunciated. "
                    "Think BBC World Service: no theatrics, no warmth, no editorial slant — "
                    "just deliver the news with professional clarity."
                ),
            )
        ],
        description=(
            "Pool of voices used for news bulletins. One is picked at random each break. "
            "Each entry has a 'voice' (TTS identifier) and optional 'voice_instructions'."
        ),
    )
    prompt_template: str | None = Field(
        default=None,
        description=(
            "Optional override for the news bulletin prompt. Placeholders: "
            "{headline_count}, {rss_source}, {headlines_block}. Leave null for the built-in default."
        ),
    )


class AdVoice(BaseModel):
    """A voice+instructions pair for ad-break narration."""

    model_config = ConfigDict(extra="forbid")

    voice: str = Field(min_length=1, description="TTS voice identifier (e.g. 'echo', 'fable').")
    voice_instructions: str | None = Field(
        default=None,
        description="Natural language delivery guidance passed to the TTS model.",
    )


class AdBreakPreferences(BaseModel):
    enabled: bool = False
    voices: list[AdVoice] = Field(
        default_factory=lambda: [AdVoice(voice="echo")],
        description=(
            "Pool of voices used for ad breaks. One is picked at random each break. "
            "Each entry has a 'voice' (TTS identifier) and optional 'voice_instructions'."
        ),
    )
    pool_size: int = Field(
        default=100,
        ge=1,
        description="Once this many unique ad clips are cached, reuse them instead of generating new ones.",
    )
    every_n_breaks: int = Field(default=6, ge=0)
    risque_chance: float = Field(
        default=0.1,
        ge=0.0,
        le=1.0,
        description=(
            "Probability (0.0–1.0) that the LLM is told to lean a little risqué/"
            "suggestive on this ad. Default 0.1 = roughly 1 in 10. Set to 0 to "
            "switch off entirely, 1.0 to always lean in."
        ),
    )
    prompt_template: str | None = Field(
        default=None,
        description=(
            "Optional override for the ad-break prompt. Placeholders: {station_name}, "
            "{station_format}, {dj_name}, {ad_category}, {ad_tone}. Leave null for "
            "the built-in default."
        ),
    )


class StationIDPreferences(BaseModel):
    """Short 'This is RadioDunc 107.2 FM' style stingers played after ad breaks.

    Phrases are generated by the LLM on first use (varied tones — classic, punchy,
    warm, etc.), cached in generated_station_ids.json, and re-generated only when
    the station name changes. To regenerate by hand, delete that file.
    """

    enabled: bool = True
    phrase_count: int = Field(
        default=40,
        ge=5,
        le=100,
        description=(
            "Target number of stinger phrases to generate per station name. "
            "Phrases are split into 5 'vibe' batches (classic / hyped / warm / "
            "cheeky / confident) generated in parallel, so the actual count is "
            "rounded up to a multiple of 5."
        ),
    )


class AlertConfig(BaseModel):
    weather_location: str = Field(
        default="Seattle, WA",
        description=(
            "Display name used in DJ weather mentions. If weather_latitude/weather_longitude "
            "are set, geocoding is skipped and this string is used purely as the spoken name."
        ),
    )
    weather_latitude: float | None = Field(
        default=None,
        description=(
            "Optional. Set this (with weather_longitude) to bypass geocoding entirely. "
            "Useful for locations the Open-Meteo geocoder doesn't recognise (small cities, "
            "suburbs, etc.). Find your coords at latlong.net or maps.google.com."
        ),
    )
    weather_longitude: float | None = Field(
        default=None,
        description="Optional. Required when weather_latitude is set.",
    )
    local_time_zone: str = "America/Los_Angeles"
    weather: WeatherPreferences = Field(default_factory=WeatherPreferences)
    news: NewsPreferences = Field(default_factory=NewsPreferences)
    ads: AdBreakPreferences = Field(default_factory=AdBreakPreferences)
    station_id: StationIDPreferences = Field(default_factory=StationIDPreferences)


WEEKDAYS = ("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")


class DJShift(BaseModel):
    """One on-air slot for a persona — a single day with start/end hours.

    A persona may have many shifts (different days, different hours). The hour
    range is inclusive on both ends and may wrap past midnight (start > end).
    """

    model_config = ConfigDict(extra="forbid")

    day: str = Field(description="Weekday name, lowercase: monday..sunday")
    start_hour: int = Field(ge=0, le=23, description="Inclusive (24h)")
    end_hour: int = Field(ge=0, le=23, description="Inclusive (24h); may wrap past midnight")

    @field_validator("day", mode="before")
    @classmethod
    def normalize_day(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("day must be a string")
        d = value.strip().lower()
        if d not in WEEKDAYS:
            raise ValueError(f"unknown weekday {value!r}; expected one of {WEEKDAYS}")
        return d


class DJPersona(BaseModel):
    """A DJ persona that can take over the station on certain shifts."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    personality: str = Field(
        min_length=1,
        description=(
            "What this persona SAYS — slang, attitude, what they'd talk about. "
            "Separate from voice/voice_instructions which control HOW they sound."
        ),
    )
    voice: str | None = None
    prompt_template: str | None = None
    voice_instructions: str | None = None
    shifts: list[DJShift] = Field(
        default_factory=list,
        description="On-air shifts. Empty means the persona is always eligible.",
    )

    @model_validator(mode="before")
    @classmethod
    def migrate_legacy_fields(cls, data):
        """Migrate two legacy shapes onto the current model in one pass.

        1. Schedule:  days + start_hour + end_hour  →  shifts list
        2. Naming:   style  →  personality (rename only, no value transform)

        Both run on load so existing radio_config.json files keep working with
        no manual edits. Once the user saves through the UI the file is
        rewritten in the new shape.
        """
        if not isinstance(data, dict):
            return data

        # Rename style → personality.
        if "personality" not in data and "style" in data:
            data["personality"] = data.pop("style")
        elif "style" in data:
            # Both present (unusual) — prefer the new name and drop the old.
            data.pop("style")

        # Schedule migration.
        if "shifts" in data and data["shifts"]:
            for key in ("days", "start_hour", "end_hour"):
                data.pop(key, None)
            return data

        days = data.pop("days", None) or []
        start = data.pop("start_hour", None)
        end = data.pop("end_hour", None)

        if not days and start is None and end is None:
            return data

        s = start if start is not None else 0
        e = end if end is not None else 23
        target_days = days if days else list(WEEKDAYS)
        data["shifts"] = [{"day": d, "start_hour": s, "end_hour": e} for d in target_days]
        return data

    @field_validator("name", "personality", mode="before")
    @classmethod
    def strip_required_text(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        if not stripped:
            raise ValueError("must not be blank")
        return stripped

    @field_validator("voice", "prompt_template", "voice_instructions", mode="before")
    @classmethod
    def normalize_optional_text(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        return stripped or None


class StationConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(default="RadioDunc", min_length=1)
    tagline: str = Field(default="Your personal AI radio station.", min_length=1)
    format: str = Field(default="Eclectic", min_length=1)
    description: str | None = None
    era: str | None = None
    genre_focus: list[str] = Field(default_factory=list)
    core_artists: list[str] = Field(default_factory=list)
    dj_name: str = Field(default="DJ", min_length=1)
    personality: str = Field(
        default="warm and conversational",
        min_length=1,
        description=(
            "What the default DJ SAYS — attitude, slang, what they'd talk about. "
            "Voice and voice_instructions control HOW they sound."
        ),
    )
    voice: str | None = None
    voice_instructions: str | None = None
    dj_prompt_template: str | None = Field(
        default=None,
        description=(
            "Optional override for the DJ transition prompt. Supports placeholders: "
            "{max_sentences}, {station_name}, {station_format}, {station_description}, "
            "{station_era}, {station_genre_focus}, {dj_name}, {personality}, "
            "{previous_track}, {next_track}, {current_time}, {current_weekday}, "
            "{weather_block}, {news_block}, {ad_block}, {reason_block}. "
            "({dj_style} is kept as an alias for {personality} for backwards compatibility.) "
            "Leave null to use the built-in default."
        ),
    )
    dj_roster: list[DJPersona] = Field(
        default_factory=list,
        description=(
            "Optional list of DJ personas with day/hour scheduling. When a persona's "
            "days/hours match the current time, it overrides dj_name/personality/voice/"
            "dj_prompt_template. Empty roster = always use the station's default DJ."
        ),
    )

    @model_validator(mode="before")
    @classmethod
    def migrate_legacy_fields(cls, data):
        """Rename legacy dj_style → personality on load. Keeps existing
        radio_config.json files working without manual edits."""
        if not isinstance(data, dict):
            return data
        if "personality" not in data and "dj_style" in data:
            data["personality"] = data.pop("dj_style")
        elif "dj_style" in data:
            data.pop("dj_style")
        return data

    @field_validator("name", "tagline", "format", "dj_name", "personality", mode="before")
    @classmethod
    def strip_required_text(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        if not stripped:
            raise ValueError("must not be blank")
        return stripped

    @field_validator("description", "era", "voice", "voice_instructions", "dj_prompt_template", mode="before")
    @classmethod
    def normalize_optional_text(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        return stripped or None


class AppConfig(BaseModel):
    music_folder: str = "~/Music"
    tts_provider: str = "tone"
    script_provider: str = "template"
    openai_api_key: str | None = None
    openai_text_model: str = "gpt-4o-mini"
    openai_tts_model: str = "gpt-4o-mini-tts"
    openai_tts_voice: str = "verse"
    playlist_artist_repeat_window: int = Field(default=3, ge=0, le=50)
    alerts: AlertConfig = Field(default_factory=AlertConfig)
    station: StationConfig = Field(default_factory=StationConfig)

    @field_validator("tts_provider", mode="before")
    @classmethod
    def normalize_tts_provider(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("must be a string")
        normalized = value.strip().lower()
        if normalized not in {"tone", "openai"}:
            raise ValueError("must be one of: tone, openai")
        return normalized

    @field_validator("openai_api_key", mode="before")
    @classmethod
    def normalize_optional_secret_text(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        return stripped or None

    @field_validator("openai_text_model", "openai_tts_model", "openai_tts_voice", mode="before")
    @classmethod
    def normalize_model_id(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("must be a string")
        stripped = value.strip()
        if not stripped:
            raise ValueError("must not be blank")
        return stripped

    @field_validator("script_provider", mode="before")
    @classmethod
    def normalize_script_provider(cls, value: str) -> str:
        if not isinstance(value, str):
            raise ValueError("must be a string")
        normalized = value.strip().lower()
        if normalized not in {"template", "openai"}:
            raise ValueError("must be one of: template, openai")
        return normalized


CONFIG_PATH = Path("radio_config.json")
EXAMPLE_CONFIG_PATH = Path("example-radio_config.json")
DOTENV_PATH = Path(".env")


def _load_dotenv_api_key() -> str | None:
    env_value = os.getenv("OPENAI_API_KEY")
    if env_value and env_value.strip():
        return env_value.strip()
    if not DOTENV_PATH.exists():
        return None
    for raw_line in DOTENV_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.strip() != "OPENAI_API_KEY":
            continue
        normalized = value.strip().strip("'").strip('"')
        return normalized or None
    return None


def _validate_and_format_config(source: str, raw_data: dict) -> AppConfig:
    try:
        return AppConfig.model_validate(raw_data)
    except ValidationError as exc:
        details = "; ".join(f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}" for err in exc.errors())
        raise ValueError(f"Invalid config in {source}: {details}") from exc


def _bootstrap_from_example_or_default() -> AppConfig:
    """Build a config from the example file if present, else AppConfig defaults."""
    if EXAMPLE_CONFIG_PATH.exists():
        data = json.loads(EXAMPLE_CONFIG_PATH.read_text(encoding="utf-8"))
        return _validate_and_format_config(str(EXAMPLE_CONFIG_PATH), data)
    return AppConfig()


def load_config() -> AppConfig:
    bootstrap_needed = not CONFIG_PATH.exists()

    if not bootstrap_needed:
        text = CONFIG_PATH.read_text(encoding="utf-8")
        if not text.strip():
            # Defensive: an empty / whitespace-only file should never exist with
            # the atomic-rename save_config below, but if something external
            # zeroed it out (manual edit, disk weirdness, killed process from
            # before the fix) we don't want to 500 every request — rebootstrap
            # silently from the example template.
            logging.getLogger(__name__).warning("radio_config.json was empty; re-bootstrapping from example template")
            bootstrap_needed = True
        else:
            try:
                data = json.loads(text)
            except json.JSONDecodeError as exc:
                logging.getLogger(__name__).warning("radio_config.json could not be parsed (%s); re-bootstrapping from example", exc)
                bootstrap_needed = True

    if bootstrap_needed:
        config = _bootstrap_from_example_or_default()
        save_config(config)
    else:
        config = _validate_and_format_config(str(CONFIG_PATH), data)

    env_api_key = _load_dotenv_api_key()
    if env_api_key:
        config = config.model_copy(update={"openai_api_key": env_api_key})
    return config


def save_config(config: AppConfig) -> None:
    """Write the config atomically: temp file + rename so concurrent readers
    never catch a partially-written or zero-byte file. POSIX rename on the
    same filesystem is atomic, so the file either contains the old bytes or
    the new bytes — never silence."""
    serialized = config.model_dump()
    serialized.pop("openai_api_key", None)
    payload = json.dumps(serialized, indent=2)

    tmp = CONFIG_PATH.with_suffix(CONFIG_PATH.suffix + ".tmp")
    tmp.write_text(payload, encoding="utf-8")
    tmp.replace(CONFIG_PATH)
